spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: frontend
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8092

