spring:
  application:
    name: user
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: dhruv_1206
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
bookstore:
  jwt:
    secret: Gq+u11XtGFPwDr2zkgrbSk7N04VsOz6Kt1RzqgWMDHqKXggb4gVDnL24/iHRR39e
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090
